version: 0.2
phases:
  install:
    runtime-versions:
      android: 29
      java: corretto8
      nodejs: 10
    commands:
      - pwd
  pre_build:
    commands:
      - echo Pre Build started
      - npm --version
      - npm install -g react-native-cli
      # - yarn
      - npm install
      - react-native link
      - cd android
      - pwd

  build:
    commands:
      - echo Build started
      # giving gradlew permission to resolve issue due to app built on windows
      - chmod +x gradlew
      - ./gradlew clean
      - ./gradlew assembleRelease
  post_build:
    commands:
      - echo Build completed!!! Please find the apk in your S3 bucket
artifacts:
  files:
    - /app/build/outputs/apk/debug/*
  discard-paths: yes
